language: rust
cache:
  - cargo: true
matrix:
  include:
    - rust: nightly
    env:
      - CLIPPY_VERSION=0.0.195
    before_script:
      - cargo install clippy --veresion $CLIPPY_VERSION || echo "clippy already installed"
    script:
      - cargo clippy
      - cargo build --verbose --all
      - cargo test --verbose --all
