language: rust
sudo: false
cache:
  - cargo: true
rust: nightly
    
env:
  global:
    - CLIPPY_VERSION=0.0.195
before_script:
  - cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo clippy
