language: rust
sudo: false
cache:
  - cargo: true
rust: 
  - nightly
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo fmt --all -- --write-mode=check
  - cargo build --verbose --all
  - cargo test --verbose --all
