[package]
name = "project_ironclad"
version = "0.1.0"
authors = ["Evan Conley <econmang@gmail.com>",
           "Jacob Cromwell <cromwellj@sou.edu>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rusoto_core = "0.31.0"
rusoto_sqs = "0.31.0"
rusoto_s3 = "031.0"
